### PR TITLE
Add haskell implementation

### PR DESCRIPTION
**Pull request by oppiliappan**
why racket when you can haskell
 - 25 sloc
 - generic
 - robust
 - equally stupid syntax

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
XD

Can you add Haskell to the list of languages in the README?

**Comment by tfidfwastaken** [comment]
well played @NerdyPepper 

peak stupid syntax is if I make my own dfa-lang in Racket while still keeping it shorter than the go implementation

but I'll give you this one, you are 2based for me, now go back to your cave

**Comment by oppiliappan** [comment]
@tfidfwastaken :^)

**Review by MadhavJivrajani — APPROVED** [review]
Thanks!

**Pull request merged**
