### PR TITLE
Simple DFA using Rust

### PR DESCRIPTION
**Pull request by AkshathaLaxmi**
Hi! I finally was able to finish DFA in Rust.

### CODE REVIEW

**Review by MadhavJivrajani — COMMENTED** [review]
It looks great to me!
IIRC, rust has a `fmt` functionality, have you run that on your code?

**Review by MadhavJivrajani — CHANGES_REQUESTED** [review]
Can you add Rust to the list of languages in `README.md`?

**Comment by AkshathaLaxmi** [comment]
> It looks great to me!
> IIRC, rust has a `fmt` functionality, have you run that on your code?

Yes, I have run fmt.

**Review by MadhavJivrajani — APPROVED** [review]
Awesome! Thanks for your PR!

**Pull request merged**
